# Generated by Django 6.0.3 on 2026-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_type',
            field=models.CharField(choices=[('bookmark', 'Bookmarked from Web'), ('manual', 'Uploaded by User')], default='bookmark', max_length=10),
        ),
    ]
